### ISSUE TITLE
Iframe issues caused by Nginx X-Frame-Options config

### ISSUE THREAD

**Issue by revagomes** [sebas5384/charm-drupal#22]
I've faced a problem with the media module when opening the media browse modal.

In the inspector console I get the following error:

```
Load denied by X-Frame-Options: http://project_name.local/media/browser?render=media-popup&types%5Bimage%5D=image&enabledPlugins%5Bmedia_default--media_browser_1%5D=media_default--media_browser_1&enabledPlugins%5Bmedia_default--media_browser_my_files%5D=media_default--media_browser_my_files&enabledPlugins%5Bmedia_internet%5D=media_internet&enabledPlugins%5Bupload%5D=upload&schemes%5Bpublic%5D=public&schemes%5Byoutube%5D=0&file_directory=&file_extensions=png+gif+jpg+jpeg&max_filesize=&uri_scheme=public&min_resolution=805x168&max_resolution=&plugins=undefined does not permit framing.
```

Adding the following line the problems was solved:

```
add_header X-Frame-Options SAMEORIGIN;
```

Maybe we could add the X-Frame-Options directive into the charm configuration. I think its a good choice because it may chance in some projects.

**Comment by sebas5384** [comment]
nice catch! thanks!
Could you tell me where to add this line? or even better, could you implement this improvement?

**Comment by revagomes** [comment]
This fix must be added into the Drupal Nginx config. As I know i was already fixed by the role maintainer so this issue could be closed.

**Comment by sebas5384** [comment]
@revagomes this seems to be already part of the role, we just needed to update the role of Drupal Nginx role.

**Comment by sebas5384** [comment]
done!
