### ISSUE TITLE
New Drupal Ngix role is broken

### ISSUE THREAD

**Issue by handrus** [sebas5384/charm-drupal#25]
I believe that with the update of #22 a bug was introduced.
Now when I try to deploy the machine I get the following error:
INFO install TASK: [pbuyle.nginx-drupal | Create available sites configuration files] *****\* 
INFO install fatal: [localhost] => {'msg': "One or more undefined variables: 'dict object' has no attribute 'limit_conn'", 'failed': True}
INFO install fatal: [localhost] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "One or more undefined variables: 'dict object' has no attribute 'limit_conn'", 'failed': True}]}

Which causes the install to fail.

**Comment by lazypower** [comment]
:thumbsup: this appears to have fixed it for me.

**Comment by handrus** [comment]
Any news here @sebas5384 ? Have you had the chance to test the PR?

**Comment by handrus** [comment]
I'm closing this issue since #26 was merged.
