### ISSUE TITLE
README makes no mention of make sync-charm-helpers to correct missing charmhelpers.contrib.ansible module on first run

### ISSUE THREAD

**Issue by lazypower** [sebas5384/charm-drupal#29]
As a new user, if I were to deploy this according to the README instructions, I would be lost as to why this is missing.

Worth noting that `make sync-charm-helpers` requires bzr to be installed prior to execution.

**Comment by sebas5384** [comment]
Thanks @chuckbutler for reporting this, and thanks to @revagomes for fixing it :) #31
